spring:
  application:
    name: greeting-service

server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'    
greeting-service:
  greeting: "Hello"
  default-value: "World"
