spring:
  application:
    name: greeting-service


management:
  endpoints:
    web:
      exposure:
        include:
        - '*'    
greeting-service:
  greeting: "TESTE"
  default-value: "Mundo"
  